// ts-app/src/pages/Todo.tsx
import  { useRef } from "react";
import TodoInput from "../components/TodoInput";
import TodoList, { TodoListInstance } from "../components/TodoList";

function Todo() {
  const todoListRef = useRef<TodoListInstance>(null);

  const handleAddTodo = (text: string) => {
    todoListRef.current?.addTodo(text);
  };

  return (
    <div>
      <h1>투두</h1>
      <TodoInput onAddTodo={handleAddTodo} />
      <TodoList ref={todoListRef} />
    </div>
  );
}

export default Todo;

// vue-app/src/pages/Todo.vue
<template>
  <div>
    <h1>투두</h1>
    <TodoInput @add-todo="addTodo" />
    <TodoList 
      :todos="todos" 
      @toggle-todo="toggleTodo"
      @delete-todo="deleteTodo"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import TodoInput from '../components/TodoInput.vue'
import TodoList from '../components/TodoList.vue'
import { Todo } from '../types'

const todos = ref<Todo[]>([])

const addTodo = (text: string) => {
  todos.value.push({ 
    id: Date.now(),
    text,
    completed: false
  })
}

const toggleTodo = (id: number) => {
  const todo = todos.value.find(t => t.id === id)
  if (todo) {
    todo.completed = !todo.completed
  }
}

const deleteTodo = (id: number) => {
  todos.value = todos.value.filter(t => t.id !== id)
}
</script>
