// vue-app/src/components/TodoInput.vue
<template>
  <div>
    <input 
      type="text" 
      v-model="newTodoText" 
      placeholder="todo" 
    />
    <button @click="handleAdd">추가</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const emit = defineEmits<{
  (e: 'add-todo', text: string): void
}>()

const newTodoText = ref('')

const handleAdd = () => {
  if (newTodoText.value.trim() !== '') {
    emit('add-todo', newTodoText.value.trim())
    newTodoText.value = ''
  }
}
</script>

// ts-app/src/components/TodoInput.tsx
import React, { useState } from "react";

interface TodoInputProps {
  onAddTodo: (text: string) => void;
}

function TodoInput({ onAddTodo }: TodoInputProps) {
  const [inputValue, setInputValue] = useState("");

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  const handleAddTodo = () => {
    if (inputValue.trim() !== "") {
      onAddTodo(inputValue);
      setInputValue("");
    }
  };

  return (
    <div>
      <input
        type="text"
        value={inputValue}
        onChange={handleInputChange}
        placeholder="todo"
      />
      <button onClick={handleAddTodo}>추가</button>
    </div>
  );
}

export default TodoInput;
