// vue-app/src/pages/About.vue
<template>
  <div>
    <h2>예제 해보기</h2>

    <input ref="inputRef" type="text" placeholder="입력하세요"/>
    <button @click="focusInput">포커스</button>

    <p>현재 카운트: {{ count }}</p>
    <button @click="count++">증가</button>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, watchEffect } from 'vue';

// React의 function About() { return (...) } 과 동일
const inputRef = ref<HTMLInputElement | null>(null);
const count = ref(0);

const focusInput = () => {
  inputRef.value?.focus();
};

watchEffect(() => { //렌더링 될 때마다 실행되는 함수
  console.log('vue 컴포넌트가 랜더링됨!');
});
</script>

<!-- Vue의 <template>안에서는 중괄호 {}를 이용해 속성에 자바스크립트 값을 전달하는 React 방식(onClick={...})이 동작하지 않습니다. 
Vue는 이를 자바스크립트 코드가 아닌 단순한 문자열(String) 인 "{() => setCount(count + 1)}"로 인식합니다. 
반면 TypeScript는 클릭 이벤트 핸들러가 함수 형태((payload: PointerEvent) => void)가 들어올 것으로 기대합니다. -->

// react-app/src/pages/About.jsx
import React from "react";
import { useRef } from "react";
import { useState } from "react";
import { useEffect } from "react";

function About() {
  const inputRef = useRef(null); //useRef 예제, 이 친구때문에 useEffect가 2번씩 렌더링 됨
  const focusInput = () => {
    inputRef.current.focus();
  };

  const [count, setCount] = useState(0); //useState 예제

  useEffect(() => {
    console.log("컴포넌트가 렌더링됨!");
  });

  return (
    <div>
      <h1>예제 해보기</h1>

      <input ref={inputRef} type="text" placeholder="입력하세요" />
      <button onClick={focusInput}>포커스</button>

      <p>현재 카운트: {count}</p>
      <button onClick={() => setCount(count + 1)}>증가</button>


    </div>
  );
}

export default About;
